spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://124.223.50.241:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto   #主键自增
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10001

logging:
  level:
    com.shigure.gulimall: debug